---
title: "Terremotos"
author: "Patricio Said"
date: "29 de mayo de 2019"
output: html_document
---

```{r }

terremotos <- readr::read_csv("https://raw.githubusercontent.com/cienciadedatos/datos-de-miercoles/master/datos/2019/2019-05-29/terremotos.csv")

mes <- readr::read_csv("https://raw.githubusercontent.com/cienciadedatos/datos-de-miercoles/master/datos/2019/2019-05-29/mes.csv")

```




```{r}
terremotos <- terremotos %>%   filter( tipo == "terremoto" ) %>% mutate(energia =10^(11.8 + 1.5 *magnitud) ) %>% 
  mutate(year1 = as.integer(year(fecha)))  %>% filter(year1 >=2000)
summary(terremotos)
max(terremotos$year1)

library(ggplot2)
#install.packages("maps")
library(maps)
#install.packages("ggthemes")
library(ggthemes)
library(gganimate)


 a <- terremotos %>%  ggplot() +
    borders("world", colour = "gray85", fill = "gray80") +
    theme_map() +
    geom_point(aes(x = longitud, y = latitud, size = energia, colour= magnitud),
            alpha= 0.9) +
   scale_colour_gradientn(colours = c("blue", "green", "yellow", "orange", "red"))+
   scale_size_continuous(range = c(2,45))+
    theme(legend.position = "none")+
     transition_states(year1, wrap = F, transition_length = 0)+
    labs(title = "Terremotos (Escala Richter >= 5.5)", subtitle = "Año: {closest_state}")
 
 
 a_gif <- animate(a, width = 470, height = 350)

 
 
 anim_save(a_gif,filename = "terremotos.gif")
  getwd()



```




# OBTENER NOMBRES DE LUGARES POR MEDIO DE COORDENADAS

```{r}
library(lubridate)
library(ggmap)

library("opencage")



output2 <- opencage_reverse(latitude = 51.5034070, 
                            longitude = -0.1275920,key = "64d5b46ffd3543139b65ce7f363189f6")
output2$rate_info %>% knitr::kable()
ciudad<- as.character(output2$results$components.city )
pais <- as.character(output2$results$components.country)
paste( ciudad, ", " , pais)
str(ciudad)

```


### intentar terremoto coquimbo , está como las weas

ver https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html

https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf




```{r}
install.packages(c("cowplot", "googleway", "ggrepel", 
                   "ggspatial", "libwgeom",  "rnaturalearth", "rnaturalearthdata"))
library("rnaturalearth")
library("rnaturalearthdata")
install.packages("rgeos")
library(rgeos)
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

ggplot(data = world) +
  theme_map()    


ggplot(world) +
  borders( colour = "gray85", fill = "gray80") +
  theme_map()


ggplot(data = world) +
  borders( colour = "red", fill = "black") +
  coord_sf( xlim = c(-83.826, -63.204),ylim = c( -23.037, -39.669), expand = FALSE)+
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid.major = element_line(color = gray(.5), linetype = "dashed", size = 0.5), panel.background = element_rect(fill = "grey"))

head(terremotos)
terremotos %>% filter(fecha == "2015-09-16") %>%  arrange(desc(magnitud))

terremoto_coquimbo <- terremotos %>% filter(fecha > "2015-07-16" & fecha < "2015-11-16") %>%  
  filter(latitud < -23.037 & latitud > -39.669) %>% filter(longitud > -83.826 & longitud < -63.204)
library(ggthemes)
library(gganimate)

terremoto_coquimbo3 %>%  ggplot() +
  borders("world", colour = "gray85", fill = "gray80") +
  theme_map() +
  geom_point(aes(x = longitud, y = latitud, size = energia, colour= magnitud),
             alpha= 0.9) +
  scale_colour_gradientn(colours = c("blue", "green", "yellow", "orange", "red"))+
  scale_size_continuous(range = c(2,45))+
  theme(legend.position = "none")+
  transition_states(fecha, wrap = F, transition_length = 0)+
  labs(title = "Terremotos (Escala Richter >= 5.5)", subtitle = "Año: {closest_state}")



fecha <- seq(as.Date("2015-07-16"), as.Date("2015-11-16"), "days")
magnitud <- rep( 0 , length(fecha))
relleno <- data.frame(fecha, magnitud)
relleno <- data.frame(fecha =seq(as.Date("2015-07-16"), as.Date("2015-11-16"), "days") )
relleno

terremoto_coquimbo3<- dplyr::full_join(terremoto_coquimbo2, relleno , by ="fecha") %>%  arrange(fecha)

terremoto_coquimbo3 <-terremoto_coquimbo3 %>%  replace(., is.na(.), 0)



```


